stages:
  - build
  - deploy

build-job:
  image: node:18
  stage: build
  script:
    - npm i yarn
    - yarn
    - npm run build
  artifacts:
    paths:
      - "public/"
      - "node_modules/"
    expire_in: 2 hours

deploy-job:
  image: node:18
  stage: deploy
  secrets:
    CLOUDFLARE_API_TOKEN:
      vault: cloudflare/worker_api_token@kv
      file: false
    CLOUDFLARE_ACCOUNT_ID:
      vault: cloudflare/worker_account_id@kv
      file: false
  script:
    - npx wrangler publish
