stages:
  - build
  - deploy

#build-job:
#  image: node:18
#  stage: build
#  script:
#    - npm i yarn
#    - yarn
#    - npm run build
#  artifacts:
#    paths:
#      - "public/"
#      - "node_modules/"
#    expire_in: 2 hours

deploy-job:
  image: node:18
  stage: deploy
  secrets:
    CLOUDFLARE_API_TOKEN:
      vault: cloudflare/worker_api_token@kv
    TEST_ENV_VAR:
      vault: 
        engine:
          name: kv-v2
          path: kv
        path: test/hello/world
        field: find_me
  script:
    #- echo $CI_JOB_JWT
    - echo $TEST_ENV_VAR
    - export VAULT_ADDR="https://vault-cluster-public-vault-e46742df.7e694688.z1.hashicorp.cloud:8200"
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=notes-app jwt=$CI_JOB_JWT)"
    - export TEST_ENV_VAR="$(vault kv get -field=find_me kv/test/hello/world)"
    - echo $TEST_ENV_VAR
    #- npx wrangler publish
